// <auto-generated />
using System;
using B221210351.EFContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace B221210351.Migrations
{
    [DbContext(typeof(HastaneContext))]
    [Migration("20231223123853_mig2")]
    partial class mig2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("B221210351.Models.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"), 1L, 1);

                    b.Property<int>("ApartmentNo")
                        .HasColumnType("int");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<int>("NeighbourhoodId")
                        .HasColumnType("int");

                    b.Property<int>("StreetId")
                        .HasColumnType("int");

                    b.HasKey("AddressId");

                    b.HasIndex("CityId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("NeighbourhoodId");

                    b.HasIndex("StreetId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            AddressId = 1,
                            ApartmentNo = 1,
                            CityId = 1,
                            DistrictId = 1,
                            NeighbourhoodId = 1,
                            StreetId = 1
                        },
                        new
                        {
                            AddressId = 2,
                            ApartmentNo = 2,
                            CityId = 1,
                            DistrictId = 2,
                            NeighbourhoodId = 2,
                            StreetId = 2
                        },
                        new
                        {
                            AddressId = 3,
                            ApartmentNo = 3,
                            CityId = 1,
                            DistrictId = 3,
                            NeighbourhoodId = 3,
                            StreetId = 3
                        });
                });

            modelBuilder.Entity("B221210351.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"), 1L, 1);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminId");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("B221210351.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"), 1L, 1);

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("PoliclinicId")
                        .HasColumnType("int");

                    b.HasKey("AppointmentId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.HasIndex("PoliclinicId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("B221210351.Models.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"), 1L, 1);

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CityId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityId = 1,
                            CityName = "İstanbul"
                        },
                        new
                        {
                            CityId = 2,
                            CityName = "Kocaeli"
                        },
                        new
                        {
                            CityId = 3,
                            CityName = "Sakarya"
                        });
                });

            modelBuilder.Entity("B221210351.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"), 1L, 1);

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            DepartmentName = "İç Hastalıkları Anabilim Dalı"
                        },
                        new
                        {
                            DepartmentId = 2,
                            DepartmentName = "Kardiyoloji Anabilim Dalı"
                        },
                        new
                        {
                            DepartmentId = 3,
                            DepartmentName = "Göğüs Hastalıkları Anabilim Dalı"
                        },
                        new
                        {
                            DepartmentId = 4,
                            DepartmentName = "Çocuk Sağlığı ve Hastalıkları Anabilim Dalı"
                        },
                        new
                        {
                            DepartmentId = 5,
                            DepartmentName = "Ruh Sağlığı ve Hastalıkları Anabilim Dalı"
                        },
                        new
                        {
                            DepartmentId = 6,
                            DepartmentName = "Nöroloji Anabilim Dalı"
                        },
                        new
                        {
                            DepartmentId = 7,
                            DepartmentName = "Deri ve Zührevi Anabilim Dalı"
                        },
                        new
                        {
                            DepartmentId = 8,
                            DepartmentName = "Genel Cerrahi Anabilim Dalı"
                        });
                });

            modelBuilder.Entity("B221210351.Models.District", b =>
                {
                    b.Property<int>("DistrictId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DistrictId"), 1L, 1);

                    b.Property<string>("DistrictName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DistrictId");

                    b.ToTable("Districts");

                    b.HasData(
                        new
                        {
                            DistrictId = 1,
                            DistrictName = "Pendik"
                        },
                        new
                        {
                            DistrictId = 2,
                            DistrictName = "Kartal"
                        },
                        new
                        {
                            DistrictId = 3,
                            DistrictName = "Maltepe"
                        });
                });

            modelBuilder.Entity("B221210351.Models.Doctor", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoctorId"), 1L, 1);

                    b.Property<string>("DoctorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DoctorSurname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<int>("PoliclinicId")
                        .HasColumnType("int");

                    b.HasKey("DoctorId");

                    b.HasIndex("PoliclinicId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            DoctorId = 1,
                            DoctorName = "Asım",
                            DoctorSurname = "Bar",
                            Gender = true,
                            PoliclinicId = 1
                        },
                        new
                        {
                            DoctorId = 2,
                            DoctorName = "Basım",
                            DoctorSurname = "Bar",
                            Gender = true,
                            PoliclinicId = 2
                        },
                        new
                        {
                            DoctorId = 3,
                            DoctorName = "Casım",
                            DoctorSurname = "Bar",
                            Gender = true,
                            PoliclinicId = 3
                        },
                        new
                        {
                            DoctorId = 4,
                            DoctorName = "Dasım",
                            DoctorSurname = "Bar",
                            Gender = true,
                            PoliclinicId = 4
                        },
                        new
                        {
                            DoctorId = 5,
                            DoctorName = "Esim",
                            DoctorSurname = "Bar",
                            Gender = true,
                            PoliclinicId = 5
                        },
                        new
                        {
                            DoctorId = 6,
                            DoctorName = "Fesim",
                            DoctorSurname = "Bar",
                            Gender = true,
                            PoliclinicId = 6
                        },
                        new
                        {
                            DoctorId = 7,
                            DoctorName = "Kesim",
                            DoctorSurname = "Bar",
                            Gender = true,
                            PoliclinicId = 7
                        },
                        new
                        {
                            DoctorId = 8,
                            DoctorName = "Lesim",
                            DoctorSurname = "Bar",
                            Gender = true,
                            PoliclinicId = 8
                        },
                        new
                        {
                            DoctorId = 9,
                            DoctorName = "Tesim",
                            DoctorSurname = "Bar",
                            Gender = true,
                            PoliclinicId = 9
                        },
                        new
                        {
                            DoctorId = 10,
                            DoctorName = "Resim",
                            DoctorSurname = "Bar",
                            Gender = true,
                            PoliclinicId = 10
                        });
                });

            modelBuilder.Entity("B221210351.Models.Neighbourhood", b =>
                {
                    b.Property<int>("NeighbourhoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NeighbourhoodId"), 1L, 1);

                    b.Property<string>("NeighbourhoodName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NeighbourhoodId");

                    b.ToTable("Neighbourhoods");

                    b.HasData(
                        new
                        {
                            NeighbourhoodId = 1,
                            NeighbourhoodName = "Güzelyalı"
                        },
                        new
                        {
                            NeighbourhoodId = 2,
                            NeighbourhoodName = "Kaynarca"
                        },
                        new
                        {
                            NeighbourhoodId = 3,
                            NeighbourhoodName = "Çamçeşme"
                        });
                });

            modelBuilder.Entity("B221210351.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"), 1L, 1);

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PatientBirthDay")
                        .HasColumnType("datetime2");

                    b.Property<string>("PatientEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PatientGender")
                        .HasColumnType("bit");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientPersonalId")
                        .HasColumnType("int");

                    b.Property<string>("PatientSurname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PatientId");

                    b.HasIndex("AddressId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("B221210351.Models.Policlinic", b =>
                {
                    b.Property<int>("PoliclinicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PoliclinicId"), 1L, 1);

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("PoliclinicName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PoliclinicId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Policlinics");

                    b.HasData(
                        new
                        {
                            PoliclinicId = 1,
                            DepartmentId = 1,
                            PoliclinicName = "Endokrinoloji ve Metabolizma Kliniği"
                        },
                        new
                        {
                            PoliclinicId = 2,
                            DepartmentId = 1,
                            PoliclinicName = "Gastroenteroloji Kliniği"
                        },
                        new
                        {
                            PoliclinicId = 3,
                            DepartmentId = 2,
                            PoliclinicName = "Kardiyoloji Kliniği"
                        },
                        new
                        {
                            PoliclinicId = 4,
                            DepartmentId = 3,
                            PoliclinicName = "Göğüs Hastalıkları Kliniği"
                        },
                        new
                        {
                            PoliclinicId = 5,
                            DepartmentId = 4,
                            PoliclinicName = "Çocuk Gastroenterolojisi Kliniği"
                        },
                        new
                        {
                            PoliclinicId = 6,
                            DepartmentId = 4,
                            PoliclinicName = "Çocuk Kardiyolojisi Kliniği"
                        },
                        new
                        {
                            PoliclinicId = 7,
                            DepartmentId = 5,
                            PoliclinicName = "Ruh Sağlığı ve Hastalıkları Kliniği"
                        },
                        new
                        {
                            PoliclinicId = 8,
                            DepartmentId = 6,
                            PoliclinicName = "Nöroloji Kliniği"
                        },
                        new
                        {
                            PoliclinicId = 9,
                            DepartmentId = 7,
                            PoliclinicName = "Deri ve Zührevi Hastalıklar Kliniği"
                        },
                        new
                        {
                            PoliclinicId = 10,
                            DepartmentId = 8,
                            PoliclinicName = "Genel Cerrahi Kliniği"
                        });
                });

            modelBuilder.Entity("B221210351.Models.Street", b =>
                {
                    b.Property<int>("StreetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StreetId"), 1L, 1);

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StreetId");

                    b.ToTable("Street");

                    b.HasData(
                        new
                        {
                            StreetId = 1,
                            StreetName = "Yavuz Selim"
                        },
                        new
                        {
                            StreetId = 2,
                            StreetName = "Teoman"
                        },
                        new
                        {
                            StreetId = 3,
                            StreetName = "Toplum"
                        });
                });

            modelBuilder.Entity("B221210351.Models.Address", b =>
                {
                    b.HasOne("B221210351.Models.City", "City")
                        .WithMany("Addresses")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("B221210351.Models.District", "District")
                        .WithMany("Addresses")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("B221210351.Models.Neighbourhood", "Neighbourhood")
                        .WithMany("Addresses")
                        .HasForeignKey("NeighbourhoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("B221210351.Models.Street", "Street")
                        .WithMany("Addresses")
                        .HasForeignKey("StreetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("District");

                    b.Navigation("Neighbourhood");

                    b.Navigation("Street");
                });

            modelBuilder.Entity("B221210351.Models.Appointment", b =>
                {
                    b.HasOne("B221210351.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("B221210351.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("B221210351.Models.Policlinic", "Policlinic")
                        .WithMany("Appointments")
                        .HasForeignKey("PoliclinicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");

                    b.Navigation("Policlinic");
                });

            modelBuilder.Entity("B221210351.Models.Doctor", b =>
                {
                    b.HasOne("B221210351.Models.Policlinic", "Policlinic")
                        .WithMany("Doctors")
                        .HasForeignKey("PoliclinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policlinic");
                });

            modelBuilder.Entity("B221210351.Models.Patient", b =>
                {
                    b.HasOne("B221210351.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("B221210351.Models.Policlinic", b =>
                {
                    b.HasOne("B221210351.Models.Department", "Department")
                        .WithMany("Policlinics")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("B221210351.Models.City", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("B221210351.Models.Department", b =>
                {
                    b.Navigation("Policlinics");
                });

            modelBuilder.Entity("B221210351.Models.District", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("B221210351.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("B221210351.Models.Neighbourhood", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("B221210351.Models.Patient", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("B221210351.Models.Policlinic", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("B221210351.Models.Street", b =>
                {
                    b.Navigation("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
